import { NextRequest, NextResponse } from 'next/server'
import type { StrategyParams } from '@/types'

interface CodeExportRequest {
  strategyId: string
  strategyName: string
  format: 'pinescript' | 'mql4' | 'mql5'
  parameters: StrategyParams
}

function generatePineScript(strategyId: string, name: string, params: StrategyParams): string {
  const paramLines = Object.entries(params)
    .map(([key, value]) => `${key} = input.int(${value}, "${key}")`)
    .join('\n')

  // Strategy-specific logic templates
  const templates: Record<string, string> = {
    'TF001': `// SMA Crossover Strategy
//@version=5
strategy("${name}", overlay=true)

${paramLines}

shortSMA = ta.sma(close, shortPeriod)
longSMA = ta.sma(close, longPeriod)

plot(shortSMA, color=color.blue, title="Short SMA")
plot(longSMA, color=color.red, title="Long SMA")

longCondition = ta.crossover(shortSMA, longSMA)
shortCondition = ta.crossunder(shortSMA, longSMA)

if (longCondition)
    strategy.entry("Long", strategy.long)

if (shortCondition)
    strategy.close("Long")`,

    'MO002': `// RSI Contrarian Strategy
//@version=5
strategy("${name}", overlay=false)

${paramLines}

rsiValue = ta.rsi(close, period)

plot(rsiValue, color=color.purple, title="RSI")
hline(oversold, "Oversold", color=color.green)
hline(overbought, "Overbought", color=color.red)

longCondition = ta.crossover(rsiValue, oversold)
shortCondition = ta.crossunder(rsiValue, overbought)

if (longCondition)
    strategy.entry("Long", strategy.long)

if (shortCondition)
    strategy.close("Long")`,

    'TF003': `// MACD Signal Strategy
//@version=5
strategy("${name}", overlay=false)

${paramLines}

[macdLine, signalLine, histLine] = ta.macd(close, fastPeriod, slowPeriod, signalPeriod)

plot(macdLine, color=color.blue, title="MACD")
plot(signalLine, color=color.orange, title="Signal")
plot(histLine, color=color.gray, style=plot.style_histogram, title="Histogram")

longCondition = ta.crossover(macdLine, signalLine)
shortCondition = ta.crossunder(macdLine, signalLine)

if (longCondition)
    strategy.entry("Long", strategy.long)

if (shortCondition)
    strategy.close("Long")`,
  }

  return templates[strategyId] || `// ${name}
//@version=5
strategy("${name}", overlay=true)

// Generated parameters
${paramLines}

// TODO: Implement strategy logic
// This is a template - please customize according to your needs`
}

function generateMQL4(strategyId: string, name: string, params: StrategyParams): string {
  const paramLines = Object.entries(params)
    .map(([key, value]) => `input int ${key} = ${value};`)
    .join('\n')

  const templates: Record<string, string> = {
    'MO002': `//+------------------------------------------------------------------+
//| ${name}                                                          |
//| Generated by StrategyLab                                         |
//+------------------------------------------------------------------+
#property copyright "StrategyLab"
#property link      ""
#property version   "1.00"
#property strict

${paramLines}

int ticket = 0;
bool inPosition = false;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   double rsiValue = iRSI(Symbol(), 0, period, PRICE_CLOSE, 0);
   double prevRsi = iRSI(Symbol(), 0, period, PRICE_CLOSE, 1);
   
   // Buy signal: RSI crosses above oversold
   if(prevRsi <= oversold && rsiValue > oversold && !inPosition)
   {
      ticket = OrderSend(Symbol(), OP_BUY, 0.1, Ask, 3, 0, 0, "${name}", 0, 0, clrGreen);
      if(ticket > 0) inPosition = true;
   }
   
   // Sell signal: RSI crosses below overbought
   if(prevRsi >= overbought && rsiValue < overbought && inPosition)
   {
      if(OrderClose(ticket, OrderLots(), Bid, 3, clrRed))
      {
         inPosition = false;
      }
   }
}`,
  }

  return templates[strategyId] || `//+------------------------------------------------------------------+
//| ${name}                                                          |
//| Generated by StrategyLab                                         |
//+------------------------------------------------------------------+
#property copyright "StrategyLab"
#property version   "1.00"
#property strict

${paramLines}

// TODO: Implement strategy logic
// This is a template - please customize according to your needs

int OnInit() { return(INIT_SUCCEEDED); }
void OnDeinit(const int reason) { }
void OnTick() { }`
}

function generateMQL5(strategyId: string, name: string, params: StrategyParams): string {
  const paramLines = Object.entries(params)
    .map(([key, value]) => `input int ${key} = ${value};`)
    .join('\n')

  return `//+------------------------------------------------------------------+
//| ${name}                                                          |
//| Generated by StrategyLab                                         |
//+------------------------------------------------------------------+
#property copyright "StrategyLab"
#property link      ""
#property version   "1.00"

#include <Trade\\Trade.mqh>
CTrade trade;

${paramLines}

int rsiHandle;
double rsiBuffer[];
bool inPosition = false;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   rsiHandle = iRSI(_Symbol, PERIOD_CURRENT, period, PRICE_CLOSE);
   ArraySetAsSeries(rsiBuffer, true);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   IndicatorRelease(rsiHandle);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   if(CopyBuffer(rsiHandle, 0, 0, 2, rsiBuffer) < 2) return;
   
   double rsiValue = rsiBuffer[0];
   double prevRsi = rsiBuffer[1];
   
   // Buy signal
   if(prevRsi <= oversold && rsiValue > oversold && !inPosition)
   {
      if(trade.Buy(0.1, _Symbol))
         inPosition = true;
   }
   
   // Sell signal
   if(prevRsi >= overbought && rsiValue < overbought && inPosition)
   {
      if(trade.Sell(0.1, _Symbol))
         inPosition = false;
   }
}`
}

export async function POST(request: NextRequest) {
  try {
    const body: CodeExportRequest = await request.json()
    const { strategyId, strategyName, format, parameters } = body

    let code: string
    let filename: string
    let contentType: string

    switch (format) {
      case 'pinescript':
        code = generatePineScript(strategyId, strategyName, parameters)
        filename = `${strategyId}_strategy.pine`
        contentType = 'text/plain'
        break
      case 'mql4':
        code = generateMQL4(strategyId, strategyName, parameters)
        filename = `${strategyId}_EA.mq4`
        contentType = 'text/plain'
        break
      case 'mql5':
        code = generateMQL5(strategyId, strategyName, parameters)
        filename = `${strategyId}_EA.mq5`
        contentType = 'text/plain'
        break
      default:
        return NextResponse.json(
          { success: false, error: 'Invalid format' },
          { status: 400 }
        )
    }

    return new NextResponse(code, {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    })
  } catch (error) {
    console.error('Code export error:', error)
    return NextResponse.json(
      { success: false, error: 'Code generation failed' },
      { status: 500 }
    )
  }
}
